/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JToggleButton;

/**
 *
 * @author Juann Inga
 */
public class VistaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VistaInicio
     */
    public VistaInicio() {
        initComponents();
        //this.setExtendedState(MAXIMIZED_BOTH);
        Desktop.setBorder(new ImagenFondo());
        this.setExtendedState(VistaInicio.MAXIMIZED_BOTH);
    }

    public JDesktopPane getDesktop() {
        return Desktop;
    }

    public void setDesktop(JDesktopPane Desktop) {
        this.Desktop = Desktop;
    }

    public JButton getTblCrudAdmin() {
        return tblCrudAdmin;
    }

    public void setTblCrudAdmin(JButton tblCrudAdmin) {
        this.tblCrudAdmin = tblCrudAdmin;
    }

    public JButton getTblCrudContratos() {
        return tblCrudContratos;
    }

    public void setTblCrudContratos(JButton tblCrudContratos) {
        this.tblCrudContratos = tblCrudContratos;
    }

    public JButton getTblCrudFacturas() {
        return tblCrudFacturas;
    }

    public void setTblCrudFacturas(JButton tblCrudFacturas) {
        this.tblCrudFacturas = tblCrudFacturas;
    }

    public JButton getTblCrudMedidores() {
        return tblCrudMedidores;
    }

    public void setTblCrudMedidores(JButton tblCrudMedidores) {
        this.tblCrudMedidores = tblCrudMedidores;
    }

    public JButton getTblCrudPersonas() {
        return tblCrudPersonas;
    }

    public void setTblCrudPersonas(JButton tblCrudPersonas) {
        this.tblCrudPersonas = tblCrudPersonas;
    }

    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator69 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        tblCrudPersonas = new javax.swing.JButton();
        jSeparator26 = new javax.swing.JToolBar.Separator();
        jSeparator27 = new javax.swing.JToolBar.Separator();
        tblCrudMedidores = new javax.swing.JButton();
        jSeparator28 = new javax.swing.JToolBar.Separator();
        jSeparator29 = new javax.swing.JToolBar.Separator();
        tblCrudContratos = new javax.swing.JButton();
        jSeparator30 = new javax.swing.JToolBar.Separator();
        jSeparator31 = new javax.swing.JToolBar.Separator();
        tblCrudFacturas = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        jSeparator57 = new javax.swing.JToolBar.Separator();
        jSeparator60 = new javax.swing.JToolBar.Separator();
        jSeparator62 = new javax.swing.JToolBar.Separator();
        jSeparator66 = new javax.swing.JToolBar.Separator();
        jSeparator73 = new javax.swing.JToolBar.Separator();
        jSeparator74 = new javax.swing.JToolBar.Separator();
        jSeparator75 = new javax.swing.JToolBar.Separator();
        jSeparator76 = new javax.swing.JToolBar.Separator();
        jSeparator77 = new javax.swing.JToolBar.Separator();
        jSeparator78 = new javax.swing.JToolBar.Separator();
        jSeparator32 = new javax.swing.JToolBar.Separator();
        jSeparator33 = new javax.swing.JToolBar.Separator();
        jSeparator15 = new javax.swing.JToolBar.Separator();
        jSeparator16 = new javax.swing.JToolBar.Separator();
        jSeparator17 = new javax.swing.JToolBar.Separator();
        jSeparator18 = new javax.swing.JToolBar.Separator();
        jSeparator19 = new javax.swing.JToolBar.Separator();
        jSeparator20 = new javax.swing.JToolBar.Separator();
        jSeparator21 = new javax.swing.JToolBar.Separator();
        jSeparator22 = new javax.swing.JToolBar.Separator();
        jSeparator23 = new javax.swing.JToolBar.Separator();
        jSeparator24 = new javax.swing.JToolBar.Separator();
        jSeparator25 = new javax.swing.JToolBar.Separator();
        jSeparator34 = new javax.swing.JToolBar.Separator();
        jSeparator35 = new javax.swing.JToolBar.Separator();
        tblCrudAdmin = new javax.swing.JButton();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        tblCrudPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/User_Group-80_icon-icons.com_57247.png"))); // NOI18N
        tblCrudPersonas.setToolTipText("Clientes");
        tblCrudPersonas.setBorder(null);
        tblCrudPersonas.setFocusable(false);
        tblCrudPersonas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tblCrudPersonas.setMaximumSize(new java.awt.Dimension(45, 45));
        tblCrudPersonas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/User_Group-80_icon-icons.com_57247.png"))); // NOI18N
        tblCrudPersonas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/User_Group-80_icon-icons.com_57247.png"))); // NOI18N
        tblCrudPersonas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tblCrudPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblCrudPersonasActionPerformed(evt);
            }
        });
        jToolBar1.add(tblCrudPersonas);
        jToolBar1.add(jSeparator26);
        jToolBar1.add(jSeparator27);

        tblCrudMedidores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gauge_115097.png"))); // NOI18N
        tblCrudMedidores.setToolTipText("Medidores");
        tblCrudMedidores.setBorder(null);
        tblCrudMedidores.setFocusable(false);
        tblCrudMedidores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tblCrudMedidores.setMaximumSize(new java.awt.Dimension(45, 45));
        tblCrudMedidores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tblCrudMedidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblCrudMedidoresActionPerformed(evt);
            }
        });
        jToolBar1.add(tblCrudMedidores);
        jToolBar1.add(jSeparator28);
        jToolBar1.add(jSeparator29);

        tblCrudContratos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1486505387-document-file-contract-agreement-certificate-degree-paper_81409.png"))); // NOI18N
        tblCrudContratos.setToolTipText("Contratos");
        tblCrudContratos.setBorder(null);
        tblCrudContratos.setFocusable(false);
        tblCrudContratos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tblCrudContratos.setMaximumSize(new java.awt.Dimension(45, 45));
        tblCrudContratos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tblCrudContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblCrudContratosActionPerformed(evt);
            }
        });
        jToolBar1.add(tblCrudContratos);
        jToolBar1.add(jSeparator30);
        jToolBar1.add(jSeparator31);

        tblCrudFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/invoice_dollar_business_document_dollar_coin_icon_150738.png"))); // NOI18N
        tblCrudFacturas.setToolTipText("Facturación");
        tblCrudFacturas.setBorder(null);
        tblCrudFacturas.setFocusable(false);
        tblCrudFacturas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tblCrudFacturas.setMaximumSize(new java.awt.Dimension(45, 45));
        tblCrudFacturas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tblCrudFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblCrudFacturasActionPerformed(evt);
            }
        });
        jToolBar1.add(tblCrudFacturas);

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jToolBar1.add(jSeparator1);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jSeparator3);
        jToolBar1.add(jSeparator4);
        jToolBar1.add(jSeparator5);
        jToolBar1.add(jSeparator6);
        jToolBar1.add(jSeparator7);
        jToolBar1.add(jSeparator8);
        jToolBar1.add(jSeparator9);
        jToolBar1.add(jSeparator10);
        jToolBar1.add(jSeparator11);
        jToolBar1.add(jSeparator12);
        jToolBar1.add(jSeparator13);
        jToolBar1.add(jSeparator14);
        jToolBar1.add(jSeparator57);
        jToolBar1.add(jSeparator60);
        jToolBar1.add(jSeparator62);
        jToolBar1.add(jSeparator66);
        jToolBar1.add(jSeparator73);
        jToolBar1.add(jSeparator74);
        jToolBar1.add(jSeparator75);
        jToolBar1.add(jSeparator76);
        jToolBar1.add(jSeparator77);
        jToolBar1.add(jSeparator78);
        jToolBar1.add(jSeparator32);
        jToolBar1.add(jSeparator33);
        jToolBar1.add(jSeparator15);
        jToolBar1.add(jSeparator16);
        jToolBar1.add(jSeparator17);
        jToolBar1.add(jSeparator18);
        jToolBar1.add(jSeparator19);
        jToolBar1.add(jSeparator20);
        jToolBar1.add(jSeparator21);
        jToolBar1.add(jSeparator22);
        jToolBar1.add(jSeparator23);
        jToolBar1.add(jSeparator24);
        jToolBar1.add(jSeparator25);
        jToolBar1.add(jSeparator34);
        jToolBar1.add(jSeparator35);

        tblCrudAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin_man_person_user_icon_127232.png"))); // NOI18N
        tblCrudAdmin.setToolTipText("Administradores");
        tblCrudAdmin.setBorder(null);
        tblCrudAdmin.setFocusable(false);
        tblCrudAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tblCrudAdmin.setMaximumSize(new java.awt.Dimension(45, 45));
        tblCrudAdmin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tblCrudAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblCrudAdminActionPerformed(evt);
            }
        });
        jToolBar1.add(tblCrudAdmin);

        Desktop.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivos");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Recursos");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ver");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Complementos");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Herramientas");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Ventana");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Ayuda");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Desktop))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Desktop.getAccessibleContext().setAccessibleParent(Desktop);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCrudAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblCrudAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCrudAdminActionPerformed

    private void tblCrudFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblCrudFacturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCrudFacturasActionPerformed

    private void tblCrudContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblCrudContratosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCrudContratosActionPerformed

    private void tblCrudMedidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblCrudMedidoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCrudMedidoresActionPerformed

    private void tblCrudPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblCrudPersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCrudPersonasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator15;
    private javax.swing.JToolBar.Separator jSeparator16;
    private javax.swing.JToolBar.Separator jSeparator17;
    private javax.swing.JToolBar.Separator jSeparator18;
    private javax.swing.JToolBar.Separator jSeparator19;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator20;
    private javax.swing.JToolBar.Separator jSeparator21;
    private javax.swing.JToolBar.Separator jSeparator22;
    private javax.swing.JToolBar.Separator jSeparator23;
    private javax.swing.JToolBar.Separator jSeparator24;
    private javax.swing.JToolBar.Separator jSeparator25;
    private javax.swing.JToolBar.Separator jSeparator26;
    private javax.swing.JToolBar.Separator jSeparator27;
    private javax.swing.JToolBar.Separator jSeparator28;
    private javax.swing.JToolBar.Separator jSeparator29;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator30;
    private javax.swing.JToolBar.Separator jSeparator31;
    private javax.swing.JToolBar.Separator jSeparator32;
    private javax.swing.JToolBar.Separator jSeparator33;
    private javax.swing.JToolBar.Separator jSeparator34;
    private javax.swing.JToolBar.Separator jSeparator35;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator57;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator60;
    private javax.swing.JToolBar.Separator jSeparator62;
    private javax.swing.JToolBar.Separator jSeparator66;
    private javax.swing.JSeparator jSeparator69;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator73;
    private javax.swing.JToolBar.Separator jSeparator74;
    private javax.swing.JToolBar.Separator jSeparator75;
    private javax.swing.JToolBar.Separator jSeparator76;
    private javax.swing.JToolBar.Separator jSeparator77;
    private javax.swing.JToolBar.Separator jSeparator78;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton tblCrudAdmin;
    private javax.swing.JButton tblCrudContratos;
    private javax.swing.JButton tblCrudFacturas;
    private javax.swing.JButton tblCrudMedidores;
    private javax.swing.JButton tblCrudPersonas;
    // End of variables declaration//GEN-END:variables
}
