/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JToggleButton;

/**
 *
 * @author Juann Inga
 */
public class VistaInicio extends javax.swing.JFrame {

    /**
     * Creates new form VistaInicio
     */
    public VistaInicio() {
        initComponents();
        //this.setExtendedState(MAXIMIZED_BOTH);
        Desktop.setBorder(new ImagenFondo());
        this.setExtendedState(VistaInicio.MAXIMIZED_BOTH);
    }

    public JDesktopPane getDesktop() {
        return Desktop;
    }

    public void setDesktop(JDesktopPane Desktop) {
        this.Desktop = Desktop;
    }

    public JButton getTblCrudAdmin() {
        return tblCrudAdmin;
    }

    public void setTblCrudAdmin(JButton tblCrudAdmin) {
        this.tblCrudAdmin = tblCrudAdmin;
    }

    public JButton getTblCrudContratos() {
        return tblCrudContratos;
    }

    public void setTblCrudContratos(JButton tblCrudContratos) {
        this.tblCrudContratos = tblCrudContratos;
    }

    public JButton getTblCrudFacturas() {
        return tblCrudFacturas;
    }

    public void setTblCrudFacturas(JButton tblCrudFacturas) {
        this.tblCrudFacturas = tblCrudFacturas;
    }

    public JButton getTblCrudMedidores() {
        return tblCrudMedidores;
    }

    public void setTblCrudMedidores(JButton tblCrudMedidores) {
        this.tblCrudMedidores = tblCrudMedidores;
    }

    public JButton getTblCrudPersonas() {
        return tblCrudPersonas;
    }

    public void setTblCrudPersonas(JButton tblCrudPersonas) {
        this.tblCrudPersonas = tblCrudPersonas;
    }

    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator69 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator36 = new javax.swing.JSeparator();
        jSeparator37 = new javax.swing.JSeparator();
        jSeparator38 = new javax.swing.JSeparator();
        jSeparator40 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        tblCrudPersonas = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        tblCrudMedidores = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        tblCrudContratos = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        tblCrudFacturas = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        jSeparator15 = new javax.swing.JToolBar.Separator();
        jSeparator16 = new javax.swing.JToolBar.Separator();
        jSeparator17 = new javax.swing.JToolBar.Separator();
        jSeparator18 = new javax.swing.JToolBar.Separator();
        jSeparator19 = new javax.swing.JToolBar.Separator();
        jSeparator20 = new javax.swing.JToolBar.Separator();
        jSeparator30 = new javax.swing.JToolBar.Separator();
        jSeparator31 = new javax.swing.JToolBar.Separator();
        jSeparator32 = new javax.swing.JToolBar.Separator();
        jSeparator33 = new javax.swing.JToolBar.Separator();
        jSeparator34 = new javax.swing.JToolBar.Separator();
        jSeparator39 = new javax.swing.JToolBar.Separator();
        jSeparator41 = new javax.swing.JToolBar.Separator();
        jSeparator42 = new javax.swing.JToolBar.Separator();
        jSeparator45 = new javax.swing.JToolBar.Separator();
        jSeparator46 = new javax.swing.JToolBar.Separator();
        jSeparator47 = new javax.swing.JToolBar.Separator();
        jSeparator48 = new javax.swing.JToolBar.Separator();
        jSeparator49 = new javax.swing.JToolBar.Separator();
        jSeparator50 = new javax.swing.JToolBar.Separator();
        jSeparator51 = new javax.swing.JToolBar.Separator();
        jSeparator52 = new javax.swing.JToolBar.Separator();
        jSeparator53 = new javax.swing.JToolBar.Separator();
        jSeparator54 = new javax.swing.JToolBar.Separator();
        jSeparator55 = new javax.swing.JToolBar.Separator();
        jSeparator56 = new javax.swing.JToolBar.Separator();
        jSeparator57 = new javax.swing.JToolBar.Separator();
        jSeparator58 = new javax.swing.JToolBar.Separator();
        jSeparator59 = new javax.swing.JToolBar.Separator();
        jSeparator60 = new javax.swing.JToolBar.Separator();
        tblCrudAdmin = new javax.swing.JButton();
        Desktop = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        barraxd = new javax.swing.JButton();
        btnAcercade1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        tblCrudPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clientes_apagado.png"))); // NOI18N
        tblCrudPersonas.setToolTipText("Clientes");
        tblCrudPersonas.setBorder(null);
        tblCrudPersonas.setContentAreaFilled(false);
        tblCrudPersonas.setFocusable(false);
        tblCrudPersonas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tblCrudPersonas.setMaximumSize(new java.awt.Dimension(50, 60));
        tblCrudPersonas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clientes.png"))); // NOI18N
        tblCrudPersonas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tblCrudPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblCrudPersonasActionPerformed(evt);
            }
        });
        jToolBar1.add(tblCrudPersonas);
        jToolBar1.add(jSeparator3);
        jToolBar1.add(jSeparator5);

        tblCrudMedidores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/medidor_apagado.png"))); // NOI18N
        tblCrudMedidores.setToolTipText("Medidores");
        tblCrudMedidores.setBorder(null);
        tblCrudMedidores.setContentAreaFilled(false);
        tblCrudMedidores.setFocusable(false);
        tblCrudMedidores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tblCrudMedidores.setMaximumSize(new java.awt.Dimension(50, 60));
        tblCrudMedidores.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/medidor.png"))); // NOI18N
        tblCrudMedidores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tblCrudMedidores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblCrudMedidoresActionPerformed(evt);
            }
        });
        jToolBar1.add(tblCrudMedidores);
        jToolBar1.add(jSeparator6);
        jToolBar1.add(jSeparator7);

        tblCrudContratos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/contrato_apagado.png"))); // NOI18N
        tblCrudContratos.setToolTipText("Contratos");
        tblCrudContratos.setBorder(null);
        tblCrudContratos.setContentAreaFilled(false);
        tblCrudContratos.setFocusable(false);
        tblCrudContratos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tblCrudContratos.setMaximumSize(new java.awt.Dimension(50, 60));
        tblCrudContratos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/contrato.png"))); // NOI18N
        tblCrudContratos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tblCrudContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblCrudContratosActionPerformed(evt);
            }
        });
        jToolBar1.add(tblCrudContratos);
        jToolBar1.add(jSeparator8);
        jToolBar1.add(jSeparator9);

        tblCrudFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/factura_apagado.png"))); // NOI18N
        tblCrudFacturas.setToolTipText("Facturación");
        tblCrudFacturas.setBorder(null);
        tblCrudFacturas.setContentAreaFilled(false);
        tblCrudFacturas.setFocusable(false);
        tblCrudFacturas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tblCrudFacturas.setMaximumSize(new java.awt.Dimension(50, 60));
        tblCrudFacturas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/factura.png"))); // NOI18N
        tblCrudFacturas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tblCrudFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblCrudFacturasActionPerformed(evt);
            }
        });
        jToolBar1.add(tblCrudFacturas);
        jToolBar1.add(jSeparator10);
        jToolBar1.add(jSeparator11);
        jToolBar1.add(jSeparator12);
        jToolBar1.add(jSeparator13);
        jToolBar1.add(jSeparator14);
        jToolBar1.add(jSeparator15);
        jToolBar1.add(jSeparator16);
        jToolBar1.add(jSeparator17);
        jToolBar1.add(jSeparator18);
        jToolBar1.add(jSeparator19);
        jToolBar1.add(jSeparator20);
        jToolBar1.add(jSeparator30);
        jToolBar1.add(jSeparator31);
        jToolBar1.add(jSeparator32);
        jToolBar1.add(jSeparator33);
        jToolBar1.add(jSeparator34);
        jToolBar1.add(jSeparator39);
        jToolBar1.add(jSeparator41);
        jToolBar1.add(jSeparator42);
        jToolBar1.add(jSeparator45);
        jToolBar1.add(jSeparator46);
        jToolBar1.add(jSeparator47);
        jToolBar1.add(jSeparator48);
        jToolBar1.add(jSeparator49);
        jToolBar1.add(jSeparator50);
        jToolBar1.add(jSeparator51);
        jToolBar1.add(jSeparator52);
        jToolBar1.add(jSeparator53);
        jToolBar1.add(jSeparator54);
        jToolBar1.add(jSeparator55);
        jToolBar1.add(jSeparator56);
        jToolBar1.add(jSeparator57);
        jToolBar1.add(jSeparator58);
        jToolBar1.add(jSeparator59);
        jToolBar1.add(jSeparator60);

        tblCrudAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin_apagado.png"))); // NOI18N
        tblCrudAdmin.setToolTipText("Administradores");
        tblCrudAdmin.setBorder(null);
        tblCrudAdmin.setContentAreaFilled(false);
        tblCrudAdmin.setFocusable(false);
        tblCrudAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tblCrudAdmin.setMaximumSize(new java.awt.Dimension(50, 60));
        tblCrudAdmin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin.png"))); // NOI18N
        tblCrudAdmin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tblCrudAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tblCrudAdminActionPerformed(evt);
            }
        });
        jToolBar1.add(tblCrudAdmin);

        Desktop.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 566, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        barraxd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/progresoxd.png"))); // NOI18N
        barraxd.setText("12,5/128,3MB");
        barraxd.setToolTipText("Uso de ram");
        barraxd.setBorder(null);
        barraxd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraxdActionPerformed(evt);
            }
        });

        btnAcercade1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/acercade.png"))); // NOI18N
        btnAcercade1.setToolTipText("Acerca de");
        btnAcercade1.setBorder(null);

        jLabel1.setText("|");

        jLabel2.setText("|");

        jPanel2.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(51, 255, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setForeground(new java.awt.Color(0, 0, 155));
        jLabel3.setText("ESP");

        jLabel4.setText("|");

        jLabel5.setText("|");

        jLabel6.setText("•••");

        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("◧ ◨ ◩ ◪ ");

        jLabel8.setText("|");

        jLabel9.setText("|");

        jLabel10.setText("Orientación:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(157, 157, 157)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(2, 2, 2)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barraxd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addComponent(jLabel6)
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(btnAcercade1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAcercade1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(barraxd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        jMenu1.setText("Archivos");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Recursos");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ver");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Complementos");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Herramientas");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Ventana");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Ayuda");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Desktop))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addComponent(Desktop))
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Desktop.getAccessibleContext().setAccessibleParent(Desktop);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblCrudFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblCrudFacturasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCrudFacturasActionPerformed

    private void tblCrudContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblCrudContratosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCrudContratosActionPerformed

    private void tblCrudMedidoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblCrudMedidoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCrudMedidoresActionPerformed

    private void tblCrudPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblCrudPersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCrudPersonasActionPerformed

    private void tblCrudAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tblCrudAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblCrudAdminActionPerformed

    private void barraxdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraxdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barraxdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JButton barraxd;
    private javax.swing.JButton btnAcercade1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator15;
    private javax.swing.JToolBar.Separator jSeparator16;
    private javax.swing.JToolBar.Separator jSeparator17;
    private javax.swing.JToolBar.Separator jSeparator18;
    private javax.swing.JToolBar.Separator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator20;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator30;
    private javax.swing.JToolBar.Separator jSeparator31;
    private javax.swing.JToolBar.Separator jSeparator32;
    private javax.swing.JToolBar.Separator jSeparator33;
    private javax.swing.JToolBar.Separator jSeparator34;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JSeparator jSeparator37;
    private javax.swing.JSeparator jSeparator38;
    private javax.swing.JToolBar.Separator jSeparator39;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator40;
    private javax.swing.JToolBar.Separator jSeparator41;
    private javax.swing.JToolBar.Separator jSeparator42;
    private javax.swing.JToolBar.Separator jSeparator45;
    private javax.swing.JToolBar.Separator jSeparator46;
    private javax.swing.JToolBar.Separator jSeparator47;
    private javax.swing.JToolBar.Separator jSeparator48;
    private javax.swing.JToolBar.Separator jSeparator49;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator50;
    private javax.swing.JToolBar.Separator jSeparator51;
    private javax.swing.JToolBar.Separator jSeparator52;
    private javax.swing.JToolBar.Separator jSeparator53;
    private javax.swing.JToolBar.Separator jSeparator54;
    private javax.swing.JToolBar.Separator jSeparator55;
    private javax.swing.JToolBar.Separator jSeparator56;
    private javax.swing.JToolBar.Separator jSeparator57;
    private javax.swing.JToolBar.Separator jSeparator58;
    private javax.swing.JToolBar.Separator jSeparator59;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator60;
    private javax.swing.JSeparator jSeparator69;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton tblCrudAdmin;
    private javax.swing.JButton tblCrudContratos;
    private javax.swing.JButton tblCrudFacturas;
    private javax.swing.JButton tblCrudMedidores;
    private javax.swing.JButton tblCrudPersonas;
    // End of variables declaration//GEN-END:variables
}
